# Changes here will be overwritten by Copier
_commit: 325b8b8
_src_path: git@github.com:python-project-templates/base.git
add_extension: python
email: 3105306+timkpaine@users.noreply.github.com
github: timkpaine
project_description: Time based function caching
project_name: temporal cache
python_version_primary: '3.11'
team: the temporal-cache authors
